language: bash

env:
  ZOO_VERSION: 3.4.11

services:
- docker

before_install:
- docker build --no-cache -t engapa/zookeeper:$ZOO_VERSION .

install:
- docker run -it --name zk -d engapa/zookeeper:$ZOO_VERSION /bin/bash -c "zk_setup.sh && ./zkServer.sh start-foreground"

script:
- sleep 10
- docker exec -it zk zk_status.sh

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push engapa/zookeeper:$ZOO_VERSION
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker build --no-cache -t engapa/zookeeper:latest;
    docker push engapa/zookeeper:latest;
  fi

after_script:
- docker stop zk
- docker rm zk
